### ISSUE TITLE
Proposal:   Make JSONlogic a stand alone module for generating expressions in Python

### ISSUE THREAD

**Issue by rogerpearce** [LLNL/clippy#14]
Basic idea for discussion:

- What we are currently calling a 'selector' would be a JSONLogic.Variable
- We could have helper functions such as:
    - JSONLogic.in
    - JSONLogic.if
    - JSONLogic.merge
    - etc ....

Also, maybe this already exists??

**Comment by sbromberger** [comment]
Closed via #16
